print("PYTHON".lower())
print("python".upper())
print("python".capitalize())
print("curso de python".title())
print("pythynjygys".replace("y", "o"))
print("a b c d e f g".split())
print("a,b,c,d,e,f,g,h,i".join(["a" "b" "c"]))
print("python".find("t"))
print("python".count("h"))
print("python".startswith("py"))
print("python".endswith("on"))